VERILOG_FILES = ../../hdl/top.v ../../hdl/picosoc/memory/spimemio.v ../../hdl/picosoc/uart/simpleuart.v ../../hdl/picosoc/picosoc.v ../../hdl/picorv32/picorv32.v
PCF_FILE = ../../hdl/pins.pcf
LDS_FILE = ../../hdl/picosoc/sections.lds
START_FILE = ../../hdl/picosoc/start.S
C_FILE = firmware.c
DEFINES = -Dgpio

include ../../hdl/tiny_soc.mk





