VERILOG_FILES = ../../hdl/top.v ../../hdl/picosoc/memory/spimemio.v ../../hdl/picosoc/uart/simpleuart.v ../../hdl/picosoc/picosoc.v ../../hdl/picorv32/picorv32.v ../../hdl/picosoc/audio/pdm_dac.v ../../hdl/picosoc/nunchuk/I2C_master.v
PCF_FILE = ../../hdl/pins.pcf
LDS_FILE = ../../firmware/sections.lds
START_FILE = ../../firmware/start.S
C_FILE = firmware.c
DEFINES = -Di2c

include ../../hdl/tiny_soc.mk





