VERILOG_FILES = ../../hdl/picosoc/hardware.v ../../hdl/picosoc/spimemio.v ../../hdl/picosoc/uart/simpleuart.v ../../hdl/picosoc/picosoc.v ../../hdl/picorv32/picorv32.v
PCF_FILE = ../../hdl/hardware.pcf
LDS_FILE = ../../hdl/picosoc/sections.lds
START_FILE = ../../hdl/picosoc/start.S
C_FILE = firmware.c

include ../../hdl/picosoc/tinyfpga.mk





