VERILOG_FILES = ../../hdl/top.v ../../hdl/picosoc/memory/spimemio.v ../../hdl/picosoc/uart/simpleuart.v ../../hdl/picosoc/picosoc.v ../../hdl/picorv32/picorv32.v ../../hdl/picosoc/vga/VGASyncGen.v ../../hdl/picosoc/vga/texture_rom.v ../../hdl/picosoc/vga/map_rom.v ../../hdl/picosoc/nunchuk/I2C_master.v ../../hdl/picosoc/audio/pdm_dac.v ../../hdl/picosoc/vga/sprite_rom.v
PCF_FILE = ../../hdl/pins.pcf
LDS_FILE = ../../firmware/sections.lds
START_FILE = ../../firmware/start.S
C_FILES = main.c ../../libraries/uart/uart.c
DEFINES = -Dvga -Di2c
INCLUDE_DIR = ../../libraries

include ../../hdl/tiny_soc.mk

