VERILOG_FILES = ../../hdl/top.v ../../hdl/picosoc/memory/spimemio.v ../../hdl/picosoc/uart/simpleuart.v ../../hdl/picosoc/picosoc.v ../../hdl/picorv32/picorv32.v ../../hdl/picosoc/vga/VGASyncGen.v
PCF_FILE = ../../hdl/hardware.pcf
LDS_FILE = ../../hdl/picosoc/sections.lds
START_FILE = ../../hdl/picosoc/start.S
C_FILE = firmware.c
DEFINES = -Dvga

include ../../hdl/tinyfpga.mk





