VERILOG_FILES = ../../hdl/top.v ../../hdl/picosoc/memory/spimemio.v ../../hdl/picosoc/uart/simpleuart.v ../../hdl/picosoc/picosoc.v ../../hdl/picorv32/picorv32.v ../../hdl/picosoc/vga/VGASyncGen.v ../../hdl/picosoc/vga/texture_rom.v ../../hdl/picosoc/vga/map_rom.v ../../hdl/picosoc/nunchuk/I2C_master.v ../../hdl/picosoc/audio/pdm_dac.v ../../hdl/picosoc/vga/sprite_rom.v
PCF_FILE = ../../hdl/hardware.pcf
LDS_FILE = ../../hdl/picosoc/sections.lds
START_FILE = ../../hdl/picosoc/start.S
C_FILE = firmware.c
DEFINES = -Dvga -Di2c

include ../../hdl/tinyfpga.mk





