VERILOG_FILES = hardware.v spimemio.v simpleuart.v picosoc.v ../picorv32/picorv32.v
PCF_FILE = ../hardware.pcf
LDS_FILE = sections.lds
START_FILE = start.S
C_FILE = firmware.c
include tinyfpga.mk





