VERILOG_FILES = ../../hdl/top.v ../../hdl/picosoc/memory/spimemio.v ../../hdl/picosoc/uart/simpleuart.v ../../hdl/picosoc/picosoc.v ../../hdl/picorv32/picorv32.v ../../hdl/picosoc/spi_oled/spi_oled.v
PCF_FILE = ../../hdl/pins.pcf
LDS_FILE = ../../firmware/sections.lds
START_FILE = ../../firmware/start.S
C_FILE = firmware.c
DEFINES = -Doled

include ../../hdl/tiny_soc.mk





